import { Category } from '../../types';

/**
 * Initial Category Seed Data for Boost Market (Epic 3 Feature 3.1 Task 3.1.1)
 *
 * Boost Market is intended for ALL TYPES OF BUSINESSES.
 * Broad business sectors covering advertising, trade, services, commerce, industry, and discovery.
 */
export const INITIAL_CATEGORY_SEEDS: Omit<Category, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'services',
    name: 'Services & Trades',
    slug: 'services',
    iconName: 'Wrench',
    description: 'Plumbing, electrical, mechanics, tailors, cleaning, tutors, and maintenance professionals',
    subcategories: ['Plumber', 'Electrician', 'Auto Mechanic', 'Tailor & Fashion Designer', 'Barber & Stylist', 'Home Cleaner', 'Tutor / Instructor', 'Repair Technician'],
    bannerImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'retail',
    name: 'Retail & Commerce',
    slug: 'retail',
    iconName: 'ShoppingBag',
    description: 'Fashion boutiques, electronics, phone gadgets, furniture, building materials, and auto parts',
    subcategories: ['Fashion & Apparel', 'Electronics & Laptops', 'Smartphones & Accessories', 'Home & Office Furniture', 'Building Materials', 'Supermarket & Groceries', 'Auto Spare Parts'],
    bannerImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'food_hospitality',
    name: 'Food, Dining & Restaurants',
    slug: 'food-restaurant',
    iconName: 'Utensils',
    description: 'Restaurants, artisan bakers, custom caterers, food vendors, bars, and dining experiences',
    subcategories: ['Restaurants & Grills', 'Artisan Bakery', 'Event Catering', 'Street Food & Snacks', 'Private Chef', 'Drink & Cocktail Service', 'Fast Food', 'Cafes & Coffee Shops'],
    bannerImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'fashion_clothing',
    name: 'Fashion & Clothing',
    slug: 'fashion-clothing',
    iconName: 'Shirt',
    description: 'Bespoke tailoring, traditional wear, ready-to-wear fashion, shoes, bags, and apparel brands',
    subcategories: ['Bespoke Tailoring', 'Traditional Attire', 'Footwear & Shoes', 'Bags & Accessories', 'Casual & Streetwear', 'Children Clothing', 'Jewelry & Watches'],
    bannerImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'creative',
    name: 'Creative, Media & Arts',
    slug: 'creative-media',
    iconName: 'Camera',
    description: 'Photographers, videographers, graphic designers, music producers, and event planners',
    subcategories: ['Studio & Event Photography', 'Cinematography & Video', 'Brand Identity & Graphic Design', 'Music & Sound Production', 'Event Planning & Decor'],
    bannerImage: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'photography_videography',
    name: 'Photography & Videography',
    slug: 'photography-videography',
    iconName: 'Video',
    description: 'Commercial photography, drone cinematography, studio portraits, video editing, and production',
    subcategories: ['Portrait Photography', 'Wedding Cinematography', 'Commercial Ad Production', 'Drone Videography', 'Photo & Video Editing'],
    bannerImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'agriculture',
    name: 'Agriculture & Farm Produce',
    slug: 'agriculture',
    iconName: 'Wheat',
    description: 'Commercial farmers, grain distributors, livestock breeders, agro-inputs, and machinery',
    subcategories: ['Crop & Grain Supply', 'Livestock & Poultry', 'Agro-Chemicals & Fertilizers', 'Farm Machinery & Tractors', 'Veterinary Services', 'Organic Produce', 'Fish Farming & Aquaculture'],
    bannerImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'professional',
    name: 'Professional & Business Services',
    slug: 'professional-services',
    iconName: 'Briefcase',
    description: 'Corporate consulting, business advisory, management consulting, and translation services',
    subcategories: ['Management Consulting', 'Business Advisory', 'HR & Recruitment', 'Translation & Interpretation', 'Public Relations'],
    bannerImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'financial_services',
    name: 'Financial Services',
    slug: 'financial-services',
    iconName: 'Banknote',
    description: 'Accounting, audit, tax advisory, insurance brokerage, wealth advisory, and financial planning',
    subcategories: ['Accounting & Bookkeeping', 'Tax Advisory', 'Audit & Assurance', 'Insurance Brokerage', 'Financial Planning & Wealth Management'],
    bannerImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'legal_services',
    name: 'Legal Services',
    slug: 'legal-services',
    iconName: 'Scale',
    description: 'Corporate law, contract drafting, litigation, intellectual property, and notary services',
    subcategories: ['Corporate & Commercial Law', 'Real Estate & Property Law', 'Intellectual Property', 'Litigation & Dispute Resolution', 'Notary Public Services'],
    bannerImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'tech_development',
    name: 'Software, IT & Technology',
    slug: 'tech-software',
    iconName: 'Code',
    description: 'Web development, mobile apps, digital marketing, cybersecurity, and cloud architecture',
    subcategories: ['Full-Stack Web Apps', 'Mobile App Development', 'SEO & Performance Marketing', 'Cloud & DevOps', 'Cybersecurity & Audits', 'UI/UX Design', 'Data Analytics'],
    bannerImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'electronics',
    name: 'Electronics & Gadgets',
    slug: 'electronics',
    iconName: 'Cpu',
    description: 'Smartphones, computer hardware, home appliances, gadgets, solar inverters, and accessories',
    subcategories: ['Smartphones & Tablets', 'Laptops & Computers', 'Solar Power & Inverters', 'Home Appliances', 'Audio & Sound Systems', 'Gadget Repair & Parts'],
    bannerImage: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'construction',
    name: 'Construction & Building',
    slug: 'construction',
    iconName: 'HardHat',
    description: 'Building contractors, civil engineering, architectural design, roofing, and structural repairs',
    subcategories: ['General Building Contractors', 'Architectural Design', 'Civil Engineering', 'Roofing & Framing', 'Tiling & Flooring', 'Plastering & Painting', 'Welding & Steel Fabrication'],
    bannerImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f6?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'real_estate',
    name: 'Real Estate & Properties',
    slug: 'real-estate',
    iconName: 'Home',
    description: 'Property sales, residential rentals, commercial leasing, land surveying, and valuation',
    subcategories: ['Residential Sales', 'Apartment Rentals', 'Commercial Leasing', 'Land Surveying', 'Property Management', 'Shortlet Apartments'],
    bannerImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'automotive',
    name: 'Automotive & Vehicles',
    slug: 'automotive',
    iconName: 'Car',
    description: 'Auto sales, mechanics, car wash, vehicle diagnostics, spare parts, and towing',
    subcategories: ['Auto Mechanic & Diagnostics', 'Car Sales & Dealership', 'Auto Spare Parts', 'Car Wash & Detailing', 'Towing Service', 'Vehicle Tinting & Wrap'],
    bannerImage: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'beauty_wellness',
    name: 'Beauty & Personal Care',
    slug: 'beauty-wellness',
    iconName: 'Sparkles',
    description: 'Skincare specialists, luxury spas, massage therapy, makeup artists, and salons',
    subcategories: ['Hair Salons & Braiding', 'Barbershops', 'Organic Skincare & Cosmetics', 'Nail Art & Pedicure', 'Bridal Makeup', 'Spa & Massage Therapy'],
    bannerImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'health_wellness',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    iconName: 'Heart',
    description: 'Clinics, dental practices, optical centers, pharmacies, physiotherapy, and wellness centers',
    subcategories: ['Medical Clinics', 'Dental Practices', 'Optical & Eye Care', 'Pharmacies & Chemist', 'Physiotherapy', 'Nutrition & Dietetics', 'Mental Wellness'],
    bannerImage: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'sports_fitness',
    name: 'Sports & Fitness',
    slug: 'sports-fitness',
    iconName: 'Dumbbell',
    description: 'Gyms, fitness centers, personal trainers, martial arts, sports academies, and equipment',
    subcategories: ['Gyms & Fitness Centers', 'Personal Trainers', 'Yoga & Pilates', 'Martial Arts & Boxing', 'Sports Coaching & Academies', 'Sports Apparel & Equipment'],
    bannerImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'education',
    name: 'Education & Training',
    slug: 'education',
    iconName: 'GraduationCap',
    description: 'Schools, private tutoring, professional certifications, vocational skills, and academies',
    subcategories: ['Private Tutoring', 'Vocational Training', 'Language School', 'Code Academy', 'Music Lessons', 'Exam Preparation'],
    bannerImage: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'transportation_logistics',
    name: 'Transportation & Logistics',
    slug: 'transportation-logistics',
    iconName: 'Truck',
    description: 'Courier delivery, interstate haulage, freight forwarding, cargo handling, and vehicle dispatch',
    subcategories: ['Same-Day Courier Delivery', 'Interstate Haulage & Trucking', 'Freight Forwarding', 'Moving & Relocation Services', 'Motorcycle Dispatch'],
    bannerImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'travel_tourism',
    name: 'Travel & Tourism',
    slug: 'travel-tourism',
    iconName: 'Plane',
    description: 'Travel agencies, visa consulting, flight booking, tour packages, and vacation rentals',
    subcategories: ['Travel Agency & Flight Booking', 'Visa Advisory & Consulting', 'Guided Tours & Excursions', 'Vacation Packages', 'Airport Transfer'],
    bannerImage: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'hospitality_events',
    name: 'Hospitality & Events',
    slug: 'hospitality-events',
    iconName: 'PartyPopper',
    description: 'Event centers, hotels, conference halls, decorators, DJs, MCs, and party rentals',
    subcategories: ['Event Centers & Venues', 'Hotels & Lodging', 'Event Decorators', 'DJs & MCs', 'Party Rentals & Canopies', 'Sound & Lighting Hire'],
    bannerImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'home_services',
    name: 'Home Services & Maintenance',
    slug: 'home-services',
    iconName: 'Hammer',
    description: 'Plumbing, electrical wiring, carpentry, painting, pest control, and generator servicing',
    subcategories: ['Generator Repairs & Servicing', 'Plumbing & Drainage', 'Electrical Wiring', 'Carpentry & Furniture Works', 'House Painting', 'Pest Control & Fumigation'],
    bannerImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing & Production',
    slug: 'manufacturing',
    iconName: 'Factory',
    description: 'Industrial manufacturing, food processing, packaging, plastics, chemicals, and textiles',
    subcategories: ['Food & Beverage Processing', 'Plastic & Packaging', 'Metal Fabrication', 'Textile & Garment Production', 'Chemical Products', 'Paper & Wood Products'],
    bannerImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'wholesale_distribution',
    name: 'Wholesale & Distribution',
    slug: 'wholesale-distribution',
    iconName: 'Boxes',
    description: 'Bulk merchandise, FMCG distribution, supply chain wholesaling, and warehouse suppliers',
    subcategories: ['FMCG & Provision Wholesalers', 'Bulk Drinks & Beverages', 'Industrial Supplies', 'Wholesale Electronics', 'Import & Export Trade'],
    bannerImage: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'cleaning_services',
    name: 'Cleaning & Facility Services',
    slug: 'cleaning-services',
    iconName: 'Sparkle',
    description: 'Commercial office cleaning, post-construction cleaning, fumigation, laundry, and dry cleaning',
    subcategories: ['Residential Deep Cleaning', 'Commercial Office Cleaning', 'Post-Construction Cleaning', 'Laundry & Dry Cleaning', 'Carpet & Upholstery Cleaning'],
    bannerImage: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'security_services',
    name: 'Security Services',
    slug: 'security-services',
    iconName: 'ShieldCheck',
    description: 'CCTV installation, security guards, alarm systems, electric fencing, and private investigation',
    subcategories: ['CCTV & Surveillance Installation', 'Uniformed Security Guards', 'Electric Fence & Access Control', 'Alarm & Fire Systems', 'Executive Protection'],
    bannerImage: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'telecommunications',
    name: 'Telecommunications',
    slug: 'telecommunications',
    iconName: 'Radio',
    description: 'Internet service providers, fiber optics, telecom infrastructure, satellite TV, and PBX systems',
    subcategories: ['Internet Service Providers (ISP)', 'Fiber Optic Installation', 'Satellite TV & Intercom', 'PBX & VoIP Phone Systems', 'SIM & Data Resellers'],
    bannerImage: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'printing_publishing',
    name: 'Printing & Publishing',
    slug: 'printing-publishing',
    iconName: 'Printer',
    description: 'Commercial printing, book publishing, banner printing, branded merchandise, and packaging boxes',
    subcategories: ['Large Format & Banner Printing', 'Branded Merchandise & Souvenirs', 'Book & Magazine Publishing', 'Paper Bags & Packaging Boxes', 'Business Cards & Flyers'],
    bannerImage: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  },
  {
    id: 'other',
    name: 'Other & General Business',
    slug: 'other',
    iconName: 'Folder',
    description: 'Specialty businesses, diverse services, and unique trade categories',
    subcategories: ['General Merchandise', 'Specialty Craft', 'Pet Care & Animals', 'Community & NGO', 'Miscellaneous Services'],
    bannerImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    status: 'active',
    active: true,
    parentId: null
  }
];
